services:
  dns-forwarder:
    container_name: dns-forwarder
    hostname: dns-forwarder
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped

    # DNS uses UDP port 53
    ports:
      - "1053:1053/udp"
      - "1067:1067/udp"
      - "1123:1123/udp"

    # Mount config so you can edit without rebuilding
    volumes:
      - ./src/DnsForwarder/appsettings.Development.json:/app/appsettings.json:ro

    # Optional: run with host networking for maximum performance
    # network_mode: host
