services:
  dns-forwarder:
    container_name: dns-forwarder
    hostname: dns-forwarder
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped

    # DNS uses UDP port 53
    ports:
      - "53:53/udp"
      - "67:67/udp"
      - "123:123/udp"

    # Mount config so you can edit without rebuilding
    volumes:
      - ./src/DnsForwarder/appsettings.Docker.json:/app/appsettings.json:ro

    # Optional: run with host networking for maximum performance
    # network_mode: host
